#
# Services definitions
#
services:
  app:
    image:  "${APP_IMAGE:-kooldev/php:8.1-nginx-sqlsrv}"
    ports:
      - "${KOOL_APP_PORT:-80}:80"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
      PHP_MAX_EXECUTION_TIME: 1900
      PHP_POST_MAX_SIZE: 500M
      PHP_MAX_INPUT_VARS: 100000
      PHP_UPLOAD_MAX_FILESIZE: 500M
      PHP_MEMORY_LIMIT: "-1"
      PHP_FPM_REQUEST_TERMINATE_TIMEOUT: "360"
      PHP_DATE_TIMEZONE: "${PHP_DATE_TIMEZONE:-UTC}"
      NGINX_CLIENT_MAX_BODY_SIZE: 500M
      NGINX_FASTCGI_READ_TIMEOUT: "120s"
      NGINX_FASTCGI_BUFFERS: 32 32k
      NGINX_FASTCGI_BUFFER_SIZE: 32k
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
    depends_on:
      - database
      - cache
    restart: always
  database:
    restart: always
    image: postgres:13-alpine
    ports:
      - "${KOOL_DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE-database}"
      POSTGRES_USER: "${DB_USERNAME-user}"
      POSTGRES_PASSWORD: "${DB_PASSWORD-pass}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - database:/var/lib/postgresql/data:delegated
    networks:
      - kool_local
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "$DB_DATABASE", "-U", "$DB_USERNAME" ]
  cache:
    restart: always
    image: redis:6-alpine
    volumes:
      - cache:/data:delegated
    networks:
      - kool_local
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

#
# Networks definitions
#
networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
volumes:
  database:
  cache:
